all:
  hosts:
    k3s-node:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
      ansible_python_interpreter: /usr/bin/python3

  children:
    k3s_cluster:
      hosts:
        k3s-node:
      vars:
        k3s_version: v1.28.5+k3s1
        k3s_server_location: /var/lib/rancher/k3s
        argocd_version: v2.9.3
