apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  labels:
    app: gitops-demo-app
spec:
  type: ClusterIP
  selector:
    app: gitops-demo-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  sessionAffinity: None
